### ISSUE TITLE
Should support webpack or browserify

### ISSUE THREAD

**Issue by prabhakarreddy1234** [rpdasilva/print-html-element#4]
Hello,

    I have been trying to use this plugin in a webpack managed package. The only problem i am facing is that the styles are not applying while printing. Because  of the below code snippet in the plugin - 

         stylesheets = Array.prototype.slice.call( document.getElementsByTagName('link') );

   It is explicitly looking for "link" elements and appending to the print html.  

For webpack or browserify enabled packages the styles are embedded into the html with "<style>" tags. So i would be happy if  i can set the option to pick "style" or "link" as per my needs...

**Comment by rpdasilva** [comment]
I don't see a need to make this an option - As per your PR, best to look for both `link` and `style` by default. An oversight on my part
