### ISSUE TITLE
header date customization

### ISSUE THREAD

**Issue by prabhakarreddy1234** [rpdasilva/print-html-element#6]
Is there any way we can localize the header date while printing.  I know a solution which is to do with changing chrome settings on the client machine. 

But i am wondering can we do it through code by passing date just like the title?

**Comment by rpdasilva** [comment]
I will look into this later on today, but I'm pretty sure the timestamp is localized to the user's browser and outside of our control

**Comment by rpdasilva** [comment]
Definitely not possible
`print-html-element` simply uses `window.print()` in the target frame which launches the system print dialog (Chrome hijacks this by using their own). It's up to the client to configure their machine's date or print timestamp settings.

I'm also not sure I see the value in programmatically being able to set the print timestamp. Its their local time of when they printed the document, I don't think this is something we should have control over.
