### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by hameddhib** [rpdasilva/print-html-element#8]
when i print from IE11 i got a blank page.

**Comment by rpdasilva** [comment]
Thanks.
I haven't done much IE testing so I will look into this

**Comment by rpdasilva** [comment]
@hameddhib sorry for the delay.

I've just done some testing in both IE11 and IE10, I don't seem to be experiencing the same issues as you, can you perhaps send me a plnkr with the same behaviour you're seeing?

See if these examples work. That's what I'm testing off of.
https://rpdasilva.github.io/print-html-element/
