### ISSUE TITLE
iframe printMode does not work in firefox

### ISSUE THREAD

**Issue by promethe42** [rpdasilva/print-html-element#9]
Tested in Firefox 45.0.1.

```javascript
PrintHTMLElement.printElement(document.getElementById('my-id'));
```

No print dialog, no error. No nothing.
This works though:

```javascript
PrintHTMLElement.printElement(
        document.getElementById('my-id'),
        { printMode: 'popup' }
);
```

I'm using React. But it works perfectly in Chrome so I'm guessing that's not the issue.

Any idea of how to fix this? Thanks!

**Comment by rpdasilva** [comment]
I'll have to look further into this, but this is confirmed as a bug.

**Comment by rpdasilva** [comment]
@promethe42 See if this branch fixes your issue
https://github.com/rpdasilva/print-html-element/tree/fix/iss9
